# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bessel_k_cpp <- function(x, nu, scaled, threads = 1L) {
    .Call(`_numericals7_bessel_k_cpp`, x, nu, scaled, threads)
}

bessel_ratio_cpp <- function(kappa, threads = 1L) {
    .Call(`_numericals7_bessel_ratio_cpp`, kappa, threads)
}

bessel_ratio_d1_cpp <- function(kappa, threads = 1L) {
    .Call(`_numericals7_bessel_ratio_d1_cpp`, kappa, threads)
}

bessel_ratio_d2_cpp <- function(kappa, threads = 1L) {
    .Call(`_numericals7_bessel_ratio_d2_cpp`, kappa, threads)
}

bessel_ratio_d3_cpp <- function(kappa, threads = 1L) {
    .Call(`_numericals7_bessel_ratio_d3_cpp`, kappa, threads)
}

bessel_ratio_d4_cpp <- function(kappa, threads = 1L) {
    .Call(`_numericals7_bessel_ratio_d4_cpp`, kappa, threads)
}

bessel_ratio_inverse_cpp <- function(rho, threads = 1L) {
    .Call(`_numericals7_bessel_ratio_inverse_cpp`, rho, threads)
}

bessel_ratio_inverse_d1_cpp <- function(kappa, threads = 1L) {
    .Call(`_numericals7_bessel_ratio_inverse_d1_cpp`, kappa, threads)
}

bessel_ratio_inverse_d2_cpp <- function(kappa, threads = 1L) {
    .Call(`_numericals7_bessel_ratio_inverse_d2_cpp`, kappa, threads)
}

bessel_ratio_inverse_d3_cpp <- function(kappa, threads = 1L) {
    .Call(`_numericals7_bessel_ratio_inverse_d3_cpp`, kappa, threads)
}

bessel_ratio_inverse_d4_cpp <- function(kappa, threads = 1L) {
    .Call(`_numericals7_bessel_ratio_inverse_d4_cpp`, kappa, threads)
}

lb_set_uk_cpp <- function(uk) {
    invisible(.Call(`_numericals7_lb_set_uk_cpp`, uk))
}

log_bessel_i_cpp <- function(x, nu, threads = 1L) {
    .Call(`_numericals7_log_bessel_i_cpp`, x, nu, threads)
}

n7_log_bessel_i_probe <- function(x, nu) {
    .Call(`_numericals7_n7_log_bessel_i_probe`, x, nu)
}

log_bessel_k_cpp <- function(x, nu) {
    .Call(`_numericals7_log_bessel_k_cpp`, x, nu)
}

student_t_cdf_cpp <- function(q, df, lower_tail, log_p, threads = 1L) {
    .Call(`_numericals7_student_t_cdf_cpp`, q, df, lower_tail, log_p, threads)
}

