# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lb_set_uk_cpp <- function(uk) {
    invisible(.Call(`_numericals7_lb_set_uk_cpp`, uk))
}

log_bessel_i_cpp <- function(x, nu) {
    .Call(`_numericals7_log_bessel_i_cpp`, x, nu)
}

log_bessel_k_cpp <- function(x, nu) {
    .Call(`_numericals7_log_bessel_k_cpp`, x, nu)
}

